# ------------------------------------------------------------------------------
# -- Pretter: 自動整形
# ------------------------------------------------------------------------------

# 1行の最大文字数を100文字に
printWidth: 100
# タブのサイズを半角スペース2つに
tabWidth: 2
# 末尾セミコロンあり
semi: true
# 末尾のカンマあり
trailingComma: "all"
# ダブルクォーテーションに統一
singleQuote: false
# JSXもダブルクォーテーション
jsxSingleQuote: false
# Arrow 関数の引数に () を付ける
arrowParens: "always"
